export type Product = {
  slug: string;
  name: string;
  category: string;
  description: string;
  price: number;
  originalPrice?: number;
  imageUrl: string;
  stock: number;
  isPrescriptionRequired: boolean;
  manufacturer?: string;
};

export const CATEGORIES = [
  { slug: "medicines", name: "Medicines" },
  { slug: "juices", name: "Health Juices & Drinks" },
  { slug: "devices", name: "Medical Devices" },
  { slug: "wellness", name: "Wellness & Supplements" },
  { slug: "otc", name: "OTC Items" },
  { slug: "first-aid", name: "First Aid" },
];

export const products: Product[] = [
  // Medicines
  {
    slug: "aspirin-500mg",
    name: "Aspirin 500mg",
    category: "medicines",
    description: "Pain relief and fever reducer. Effective for headaches, muscle aches, and minor arthritis pain.",
    price: 45,
    originalPrice: 60,
    imageUrl: "/product-images/medicines/aspirin.svg",
    stock: 150,
    isPrescriptionRequired: false,
    manufacturer: "PharmaCare Labs",
  },
  {
    slug: "amoxicillin-250mg",
    name: "Amoxicillin 250mg",
    category: "medicines",
    description: "Broad-spectrum antibiotic. Used to treat bacterial infections including ear, nose, throat, and urinary tract infections.",
    price: 85,
    originalPrice: 120,
    imageUrl: "/product-images/medicines/amoxicillin.svg",
    stock: 80,
    isPrescriptionRequired: true,
    manufacturer: "MediCure Pharmaceuticals",
  },
  {
    slug: "paracetamol-500mg",
    name: "Paracetamol 500mg",
    category: "medicines",
    description: "Acetaminophen pain reliever and fever reducer. Gentle on stomach, suitable for all ages.",
    price: 35,
    originalPrice: 50,
    imageUrl: "/product-images/medicines/paracetamol.svg",
    stock: 200,
    isPrescriptionRequired: false,
    manufacturer: "GlobalHealth Inc",
  },
  {
    slug: "omeprazole-20mg",
    name: "Omeprazole 20mg",
    category: "medicines",
    description: "Reduces stomach acid production. Treats heartburn, GERD, and peptic ulcers.",
    price: 120,
    originalPrice: 180,
    imageUrl: "/product-images/medicines/omeprazole.svg",
    stock: 60,
    isPrescriptionRequired: true,
    manufacturer: "GastroMed Solutions",
  },
  {
    slug: "metformin-500mg",
    name: "Metformin 500mg",
    category: "medicines",
    description: "Controls blood sugar in diabetes. First-line treatment for Type 2 diabetes.",
    price: 95,
    originalPrice: 140,
    imageUrl: "/product-images/medicines/metformin.svg",
    stock: 100,
    isPrescriptionRequired: true,
    manufacturer: "DiabetesControl Corp",
  },
  {
    slug: "cetirizine-10mg",
    name: "Cetirizine 10mg",
    category: "medicines",
    description: "Antihistamine for allergies. Reduces sneezing, runny nose, and itchy eyes.",
    price: 55,
    imageUrl: "/product-images/medicines/cetirizine.svg",
    stock: 120,
    isPrescriptionRequired: false,
    manufacturer: "AllergyRelief Ltd",
  },
  {
    slug: "ibuprofen-400mg",
    name: "Ibuprofen 400mg",
    category: "medicines",
    description: "Anti-inflammatory pain reliever. Effective for muscle pain, period cramps, and minor injuries.",
    price: 65,
    originalPrice: 85,
    imageUrl: "/product-images/medicines/ibuprofen.svg",
    stock: 140,
    isPrescriptionRequired: false,
    manufacturer: "PainEase International",
  },
  {
    slug: "loratadine-10mg",
    name: "Loratadine 10mg",
    category: "medicines",
    description: "Non-drowsy antihistamine for allergies, hay fever, and hives.",
    price: 75,
    imageUrl: "/product-images/medicines/loratadine.svg",
    stock: 90,
    isPrescriptionRequired: false,
    manufacturer: "ClearSinus Pharma",
  },

  // Health Juices & Drinks
  {
    slug: "aloe-vera-juice",
    name: "Pure Aloe Vera Juice",
    category: "juices",
    description: "100% pure aloe vera juice. Supports digestive health and boosts immunity naturally.",
    price: 250,
    originalPrice: 350,
    imageUrl: "/product-images/juices/aloe-vera-juice.svg",
    stock: 50,
    isPrescriptionRequired: false,
    manufacturer: "NatureGreen Beverages",
  },
  {
    slug: "immunity-booster-juice",
    name: "Immunity Booster Juice - Real",
    category: "juices",
    description: "Real brand juice. Orange, lemon, ginger, and turmeric blend. Strengthens immunity and fights infection.",
    price: 180,
    originalPrice: 250,
    imageUrl: "/product-images/juices/real.svg",
    stock: 70,
    isPrescriptionRequired: false,
    manufacturer: "Real Juices",
  },
  {
    slug: "neem-juice",
    name: "Neem Juice",
    category: "juices",
    description: "Detoxifying neem juice. Traditional remedy for blood purification and skin health.",
    price: 220,
    imageUrl: "/product-images/juices/neem-juice.svg",
    stock: 40,
    isPrescriptionRequired: false,
    manufacturer: "AyurvedaWellness Co",
  },
  {
    slug: "maza-juice",
    name: "Maza Juice - Mixed Fruit",
    category: "juices",
    description: "Maza brand mixed fruit juice. Refreshing blend of tropical fruits, perfect for family.",
    price: 120,
    originalPrice: 150,
    imageUrl: "/product-images/juices/maza.svg",
    stock: 85,
    isPrescriptionRequired: false,
    manufacturer: "Maza Beverages",
  },
  {
    slug: "frooty-juice",
    name: "Frooty Juice - Tropical",
    category: "juices",
    description: "Frooty brand tropical juice. Delicious taste with natural fruit extracts.",
    price: 110,
    originalPrice: 140,
    imageUrl: "/product-images/juices/frooty.svg",
    stock: 95,
    isPrescriptionRequired: false,
    manufacturer: "Frooty",
  },
  {
    slug: "minute-maid-juice",
    name: "Minute Maid - Orange Juice",
    category: "juices",
    description: "Minute Maid premium orange juice. 100% natural, fresh, and energizing.",
    price: 150,
    originalPrice: 200,
    imageUrl: "/product-images/juices/minute-maid.svg",
    stock: 65,
    isPrescriptionRequired: false,
    manufacturer: "Minute Maid",
  },

  // Medical Devices
  {
    slug: "digital-thermometer",
    name: "Digital Thermometer",
    category: "devices",
    description: "Fast and accurate temperature reading. Ideal for all ages, including infants.",
    price: 350,
    originalPrice: 500,
    imageUrl: "/product-images/devices/digital-thermometer.svg",
    stock: 100,
    isPrescriptionRequired: false,
    manufacturer: "MedTech Pro",
  },
  {
    slug: "blood-pressure-monitor",
    name: "Automatic Blood Pressure Monitor",
    category: "devices",
    description: "Digital BP monitor for home use. Easy-to-read display and memory storage.",
    price: 1200,
    originalPrice: 1800,
    imageUrl: "/product-images/devices/blood-pressure-monitor.svg",
    stock: 30,
    isPrescriptionRequired: false,
    manufacturer: "CardioMonitor Tech",
  },
  {
    slug: "pulse-oximeter",
    name: "Finger Pulse Oximeter",
    category: "devices",
    description: "Measures oxygen saturation and heart rate. Compact and portable design.",
    price: 800,
    originalPrice: 1200,
    imageUrl: "/product-images/devices/pulse-oximeter.svg",
    stock: 45,
    isPrescriptionRequired: false,
    manufacturer: "OxyHealth Systems",
  },
  {
    slug: "glucose-meter",
    name: "Glucose Meter with Test Strips",
    category: "devices",
    description: "Accurate blood glucose testing. Quick results for diabetes management.",
    price: 950,
    imageUrl: "/product-images/devices/digital-thermometer.svg",
    stock: 50,
    isPrescriptionRequired: false,
    manufacturer: "DiabetesCare Pro",
  },
  {
    slug: "heating-pad",
    name: "Electric Heating Pad",
    category: "devices",
    description: "Soothing heat therapy for muscle pain and stiffness. Multiple temperature settings.",
    price: 650,
    imageUrl: "/product-images/devices/blood-pressure-monitor.svg",
    stock: 40,
    isPrescriptionRequired: false,
    manufacturer: "ComfortCare Ltd",
  },

  // Wellness & Supplements
  {
    slug: "vitamin-c-1000mg",
    name: "Vitamin C 1000mg",
    category: "wellness",
    description: "Immune support supplement. Supports collagen production and antioxidant defense.",
    price: 180,
    originalPrice: 250,
    imageUrl: "/product-images/medicines/aspirin.svg",
    stock: 120,
    isPrescriptionRequired: false,
    manufacturer: "VitaminMax Supplements",
  },
  {
    slug: "multivitamin-daily",
    name: "Daily Multivitamin",
    category: "wellness",
    description: "Complete daily nutrition with essential vitamins and minerals for overall health.",
    price: 220,
    originalPrice: 300,
    imageUrl: "/product-images/medicines/cetirizine.svg",
    stock: 100,
    isPrescriptionRequired: false,
    manufacturer: "HealthComplete Co",
  },
  {
    slug: "fish-oil-omega3",
    name: "Fish Oil Omega-3",
    category: "wellness",
    description: "Supports heart health and cognitive function. High-quality fish oil supplement.",
    price: 350,
    imageUrl: "/product-images/medicines/ibuprofen.svg",
    stock: 60,
    isPrescriptionRequired: false,
    manufacturer: "OceanHealth Labs",
  },
  {
    slug: "probiotics",
    name: "Probiotic Supplement",
    category: "wellness",
    description: "Gut health support with beneficial bacteria strains. Improves digestion and immunity.",
    price: 280,
    originalPrice: 400,
    imageUrl: "/product-images/medicines/metformin.svg",
    stock: 70,
    isPrescriptionRequired: false,
    manufacturer: "GutHealth Pro",
  },
  {
    slug: "zinc-supplement",
    name: "Zinc Supplement 30mg",
    category: "wellness",
    description: "Boosts immunity and supports wound healing. Essential mineral for health.",
    price: 150,
    imageUrl: "/product-images/medicines/loratadine.svg",
    stock: 90,
    isPrescriptionRequired: false,
    manufacturer: "MineralHealth Co",
  },
  {
    slug: "iron-supplement",
    name: "Iron Supplement",
    category: "wellness",
    description: "Treats iron deficiency anemia. Supports energy levels and blood health.",
    price: 170,
    imageUrl: "/product-images/medicines/omeprazole.svg",
    stock: 75,
    isPrescriptionRequired: false,
    manufacturer: "AnemiaCare Solutions",
  },

  // OTC Items
  {
    slug: "surgical-masks-50pack",
    name: "Surgical Masks - 50 Pack",
    category: "otc",
    description: "3-ply disposable surgical masks. Protection and comfort for daily use.",
    price: 250,
    originalPrice: 350,
    imageUrl: "/product-images/medicines/aspirin.svg",
    stock: 200,
    isPrescriptionRequired: false,
    manufacturer: "SafeShield Medical",
  },
  {
    slug: "hand-sanitizer-500ml",
    name: "Hand Sanitizer 500ml",
    category: "otc",
    description: "70% alcohol-based sanitizer. Kills 99.9% germs instantly without water.",
    price: 120,
    originalPrice: 180,
    imageUrl: "/product-images/juices/real.svg",
    stock: 150,
    isPrescriptionRequired: false,
    manufacturer: "GermFree Labs",
  },
  {
    slug: "antiseptic-solution-500ml",
    name: "Antiseptic Solution 500ml",
    category: "otc",
    description: "Betadine solution for cuts and wounds. Disinfects and prevents infection.",
    price: 95,
    imageUrl: "/product-images/medicines/paracetamol.svg",
    stock: 100,
    isPrescriptionRequired: false,
    manufacturer: "WoundCare Pro",
  },
  {
    slug: "antibiotic-ointment",
    name: "Antibiotic Ointment",
    category: "otc",
    description: "Triple antibiotic ointment for minor cuts. Prevents infection and aids healing.",
    price: 85,
    imageUrl: "/product-images/medicines/metformin.svg",
    stock: 120,
    isPrescriptionRequired: false,
    manufacturer: "MediHeal Solutions",
  },
  {
    slug: "cotton-swabs-200pack",
    name: "Cotton Swabs - 200 Pack",
    category: "otc",
    description: "Soft cotton buds for cleaning and care. Multi-purpose use.",
    price: 45,
    imageUrl: "/product-images/medicines/cetirizine.svg",
    stock: 250,
    isPrescriptionRequired: false,
    manufacturer: "CleanCare Basic",
  },
  {
    slug: "gauze-pads-100pack",
    name: "Sterile Gauze Pads - 100 Pack",
    category: "otc",
    description: "Sterile gauze for wound care and dressing. Highly absorbent.",
    price: 150,
    imageUrl: "/product-images/medicines/amoxicillin.svg",
    stock: 100,
    isPrescriptionRequired: false,
    manufacturer: "MedicalSupply Pro",
  },

  // First Aid
  {
    slug: "first-aid-kit-home",
    name: "Home First Aid Kit",
    category: "first-aid",
    description: "Comprehensive first aid kit for home. Includes bandages, creams, and tools.",
    price: 850,
    originalPrice: 1200,
    imageUrl: "/product-images/devices/digital-thermometer.svg",
    stock: 40,
    isPrescriptionRequired: false,
    manufacturer: "SafetyFirst Co",
  },
  {
    slug: "elastic-bandage-3pack",
    name: "Elastic Bandage - 3 Pack",
    category: "first-aid",
    description: "Stretchable bandages for sprains and support. Adjustable compression.",
    price: 180,
    imageUrl: "/product-images/medicines/ibuprofen.svg",
    stock: 80,
    isPrescriptionRequired: false,
    manufacturer: "CompressiteCare",
  },
  {
    slug: "adhesive-bandages-mixed",
    name: "Adhesive Bandages Assorted",
    category: "first-aid",
    description: "Mixed sizes of sterile adhesive bandages. Quick relief for minor cuts.",
    price: 120,
    imageUrl: "/product-images/medicines/paracetamol.svg",
    stock: 150,
    isPrescriptionRequired: false,
    manufacturer: "StripCare Plus",
  },
  {
    slug: "pain-relief-cream",
    name: "Muscle Pain Relief Cream",
    category: "first-aid",
    description: "Topical pain relief for muscles and joints. Menthol-based formula.",
    price: 250,
    imageUrl: "/product-images/medicines/omeprazole.svg",
    stock: 70,
    isPrescriptionRequired: false,
    manufacturer: "ReliefRub Inc",
  },
  {
    slug: "ice-pack-reusable",
    name: "Reusable Ice Pack",
    category: "first-aid",
    description: "Gel-based ice pack for swelling and pain relief. Stays cold for hours.",
    price: 280,
    imageUrl: "/product-images/devices/pulse-oximeter.svg",
    stock: 50,
    isPrescriptionRequired: false,
    manufacturer: "ColdComfort Labs",
  },
];
