[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
